services:
  adminer:
    deploy:
      labels:
      - traefik.enable=true
      - traefik.http.routers.adminer.middlewares=redirectscheme
      - traefik.http.routers.adminer.rule=Host(`adminer.mcleut.de`)
      - traefik.http.routers.adminer_secure.rule=Host(`adminer.mcleut.de`)
      - traefik.http.services.adminer.loadbalancer.server.port=8080
      - traefik.http.routers.adminer_secure.middlewares=auth
      - traefik.http.routers.adminer_secure.tls.certresolver=default
    image: adminer:latest
    volumes:
    - /production/adminer.css:/var/www/html/adminer.css:ro

  bitwarden:
    deploy:
      labels:
      - traefik.enable=true
      - traefik.http.routers.bitwarden.middlewares=redirectscheme
      - traefik.http.routers.bitwarden.rule=Host(`bitwarden.mcleut.de`)
      - traefik.http.routers.bitwarden_secure.rule=Host(`bitwarden.mcleut.de`)
      - traefik.http.services.bitwarden.loadbalancer.server.port=80
#     - traefik.http.routers.bitwarden_secure.middlewares=auth
      - traefik.http.routers.bitwarden_secure.tls.certresolver=default
    image: bitwardenrs/server:latest
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro 
    - /production/bitwarden_data:/data
